### ISSUE TITLE
Feature request: Allow non-JSON schemas in Feature flags

### ISSUE THREAD

**Issue by whardier** [aws-powertools/powertools-lambda-python#1170]
**Is your feature request related to a problem? Please describe.**

Allow for callable transforms to be used (as well as the str "shortcuts").

**Describe the solution you'd like**

Pass something like yaml.loads or load_my_really_cool_serialized_data callable as transform argument toward parameter store fetches.

**Describe alternatives you've considered**

Due to how feature flags works.. we are unable to use yaml or any other loader before processing happens and this needs patched.  Other approaches for parameters is to not pass a transform and then transform after the fact.

**Additional context**

PR already written up.

**Comment by heitorlessa** [comment]
Update: Now that feature flags is stable (one incoming change for [Time-based feature](#1666)), I'd love to see a RFC on this for a Loader interface so to allow any input (YAML, TOML, canonical, etc.).

**Comment by leandrodamascena** [comment]
Hi @whardier! Hope things are going well over there.

It's been a long time since we've had updates on this issue, and we'd like to know if you can work on an RFC to implement this in Powertools. As @heitorlessa mentioned, the `Feature Flags` is stable and we have support to TimeBased - #1554 and Module Range - #2003, it can be awesome to add support for input other than JSON only.

Thank you.

**Comment by heitorlessa** [comment]
We're closing feature requests older than a year that haven't received enough customers +1 or that we were unable to prioritize. For newer customers interested in, please feel free to comment and we can reopen it.
